name: dart_gsheet_remote_config
description: A package that allows you to use Google Sheets as a remote config for changing your Dart/Flutter app's behaviors, settings,.. without updating.
version: 1.2.1+2
topics: [remote, config]
repository: https://github.com/dungngminh/dart_gsheet_remote_config

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
  mockito: ^5.4.4
